
typedef enum{
    FRONT_POWER_DIST_EVENT_DRIVER_DISPLAY = 0,
    FRONT_POWER_DIST_EVENT_STEERING,
    FRONT_POWER_DIST_EVENT_CENTRE_CONSOLE,
    FRONT_POWER_DIST_EVENT_PEDAL,
    FRONT_POWER_DIST_EVENT_FRONT_LIGHTS,
    FRONT_POWER_DIST_EVENT_DASHBOARD_INDICATOR,
    FRONT_POWER_DIST_EVENT_HORN,
    FRONT_POWER_DIST_EVENT_DRIVER_FANS,
    NUM_FRONT_POWER_DIST_EVENTS
}FrontPowerDistEvent;